


Resources:
  SSMROLE:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: 'sts:AssumeRole'
      Policies: 'arn:aws:iam::aws:policy/AmazonSSMFullAccess'

Outputs:
  WebELBURL:
    Description: The Role Arn
    Value: 
      !GetAtt SSMROLE.Arn